/**
 * 每个Prefab中的节点引用路径。请不要手动修改此文件内容!!!
 * 
 * This file is automatically generated, please do not edit it!!!
 */
export const NodePaths = {

	GameScenePrefab: {
		SpriteSplash: "SpriteSplash",
		Label: "Label",
		Button: "Button",
		Button_Label: "Button/Label",
		PopupBtn: "PopupBtn",
		PopupBtn_Label: "PopupBtn/Label",
	},

	LoadingViewPrefab: {
		SpriteSplash: "SpriteSplash",
		ProgressBar: "ProgressBar",
		ProgressBar_Bar: "ProgressBar/Bar",
	},

	MainScenePrefab: {
		Label: "Label",
		Sprite: "Sprite",
		Button: "Button",
		Button_Label: "Button/Label",
	},

};
