/**
 * 每个Bundle中的资源引用路径。请不要手动修改此文件内容!!!
 * 
 * This file is automatically generated, please do not edit it!!!
 */
export const ResPaths = {

	GameBundle: {
		GameScenePrefab: "GameBundle/GameScene",
	},

	MainBundle: {
		LoadingViewPrefab: "MainBundle/LoadingView",
		MainScenePrefab: "MainBundle/MainScene",
		EnJson: "MainBundle/Res/Lang/Lable/en",
		ZhJson: "MainBundle/Res/Lang/Lable/zh",
	},

};
