/**
 * 每个Bundle中的资源引用路径。请不要手动修改此文件内容!!!
 * 
 * This file is automatically generated, please do not edit it!!!
 */
export const ResPaths = {

	GameBundle: {
		ChessBoardPrefab: "GameBundle/ChessBoard",
		ChessContainerPrefab: "GameBundle/ChessContainer",
		GameScenePrefab: "GameBundle/GameScene",
		B_boxPng: "GameBundle/Res/Chess/b_box/spriteFrame",
		B_cPng: "GameBundle/Res/Chess/b_c/spriteFrame",
		B_jPng: "GameBundle/Res/Chess/b_j/spriteFrame",
		B_mPng: "GameBundle/Res/Chess/b_m/spriteFrame",
		B_pPng: "GameBundle/Res/Chess/b_p/spriteFrame",
		B_sPng: "GameBundle/Res/Chess/b_s/spriteFrame",
		B_xPng: "GameBundle/Res/Chess/b_x/spriteFrame",
		B_zPng: "GameBundle/Res/Chess/b_z/spriteFrame",
		ChessboardPng: "GameBundle/Res/Chess/chessboard/spriteFrame",
		R_boxPng: "GameBundle/Res/Chess/r_box/spriteFrame",
		R_cPng: "GameBundle/Res/Chess/r_c/spriteFrame",
		R_jPng: "GameBundle/Res/Chess/r_j/spriteFrame",
		R_mPng: "GameBundle/Res/Chess/r_m/spriteFrame",
		R_pPng: "GameBundle/Res/Chess/r_p/spriteFrame",
		R_sPng: "GameBundle/Res/Chess/r_s/spriteFrame",
		R_xPng: "GameBundle/Res/Chess/r_x/spriteFrame",
		R_zPng: "GameBundle/Res/Chess/r_z/spriteFrame",
	},

	LoadingBundle: {
		LoadingViewPrefab: "LoadingBundle/LoadingView",
	},

	MainBundle: {
		MainScenePrefab: "MainBundle/MainScene",
		PopupDemo1Prefab: "MainBundle/PopupDemo1",
		EnJson: "MainBundle/Res/Lang/Lable/en",
		ZhJson: "MainBundle/Res/Lang/Lable/zh",
	},

};
