/**
 * 每个Prefab中的节点引用路径。请不要手动修改此文件内容!!!
 * 
 * This file is automatically generated, please do not edit it!!!
 */
export const NodePaths = {

	LoadingViewPrefab: {
		"SpriteSplash": "SpriteSplash",
		"ProgressBar": "ProgressBar",
		"ProgressBar_Bar": "ProgressBar/Bar",
		"logo": "logo",
	},

	MainScenePrefab: {
	},

};
